#!/bin/sh

black_formatting_results=$(poetry run black --check --line-length 100 . 2>&1 > /dev/null)
if [[ "$?" == "0" ]]; then
    echo "✅ Source Code Formatting"
else
    echo "❌ Source Code Formatting"
    echo "$black_formatting_results"
	exit 1
fi

prettier_formatting_results=$(npx --yes prettier@3.0.3 . --no-config --check --log-level warn 2>&1 >/dev/null)
if [[ "$?" == "0" ]]; then
    echo "✅ Supplemental Code Formatting"
else
    echo "❌ Supplemental Code Formatting"
    echo "$prettier_formatting_results"
	exit 1
fi

python_linting_results=$(poetry run pylint src tests)
if [[ "$?" == "0" ]]; then
    echo "✅ Python Linting"
else
    echo "❌ Python Linting"
    echo "$python_linting_results"
	exit 1
fi

gh_actions_linting_results=$(act --dryrun)
if [[ "$?" == "0" ]]; then
    echo "✅ GitHub Actions Linting"
else
    echo "❌ GitHub Actions Linting"
    echo "$gh_actions_linting_results"
	exit 1
fi

test_results=$(poetry run pytest tests/unit tests/integration --cov=src/package_name --cov-fail-under=90 --no-header --no-summary -qq --cov=src/package_name --cov-report term-missing:skip-covered --cov-branch --cov-fail-under=90)
if [[ "$?" == "0" ]]; then
	echo "✅ Unit/Integration Tests"
else
	echo "❌ Unit/Integration Tests"
	echo "$test_results"
	exit 1
fi