#!/bin/sh

test_results=$(poetry run pytest --no-header -qq tests --cov-fail-under=90)
if [[ "$?" == "0" ]]; then
	echo "✅ Integration Tests"
else
	echo "❌ Integration Tests"
	echo "$test_results"
	exit 1
fi