name: Scan, Lint and Test Source Code

on:
  workflow_dispatch:

  pull_request:

  push:
    branches: ['main']

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Run Vulnerability Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload Snyk Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - name: Install Python Dependencies
        run: poetry install

      - name: Check Formatting
        run: poetry run black --check --line-length 100 .

      - name: Lint Code
        run: poetry run pylint src tests

      - name: Run Unit and Integration Tests
        run: poetry run pytest tests
