name: Continuous Delivery

on:
  workflow_dispatch:

  pull_request_target:
    types: ["closed"]
    branches: ["main"]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "poetry"

      - name: Install Python Dependencies
        run: poetry install

      - name: Run End-to-End Tests
        run: poetry run pytest tests/e2e

      - name: Bump Version
        id: bump-version
        run: |
          package_version="$(poetry version ${{ startsWith(env.BRANCH_NAME, 'bug') || startsWith(env.BRANCH_NAME, 'fix') && 'patch' || 'minor' }} --short)"
          git config user.name ccc-service-account
          git config user.email service@cloudcitycrafted.io
          git commit -am "chore: Bump package version to v$package_version"
          git push
          echo "new-version=$package_version" >> $GITHUB_OUTPUT

      - name: Build Package
        run: poetry build

      - name: Create GitHub Release
        run: gh release create --generate-notes --latest 'v${{ steps.bump-version.outputs.new-version }}' ./dist/*.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
