name: Run e2e Testing

on:
  workflow_dispatch:

  pull_request_target:
    types: ['closed']
    branches: ['main']

jobs:
  e2e-tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'

      - name: Install Python Dependencies
        run: poetry install

      - name: Run e2e Tests
        run: poetry run pytest tests/e2e
